# Nav
social:
  Github: https://github.com/ZXKitCode
  Blog: http://blog.hudongdong.com/

# Footer
footerSocial:
  email: mailto://dong765@qq.com
  github: https://github.com/ZXKitCode
  
# Background image, color
background: 'url(https://cdn.jsdelivr.net/gh/frontendsophie/hexo-theme-autumn@1.0.0/source/img/button-bg.png) #f3f3f3'

# Favicon
favicon: https://zxkit.com/img/favicon.ico

# SEO
keywords: 'zxkit,ios,debug,debug-tool,swift,kit'

# Widgets, enable at least one
widgets:
  category: enabled
  archive: enabled
  tag: enabled

# Set the first image in post to cover
auto_cover: true

# post page show widget
postWidget: false
# use highlightjs to render
highlightjs: true
showLineNum: true